### ISSUE TITLE
Does this really work for android?

### ISSUE THREAD

**Issue by pistonsky** [kyo504/react-native-marquee#14]
We use this lib in our project, and everything works fine for iOS. However, on Android the text doesn't move at all. Well, it moves, but with a huge delay, even if I set `marqueeDelay` to 0. I think when there is a big number of marquee texts rendered, they start to behave this weird way.

**Comment by rohit-ganapathy** [comment]
any status update on this? Really looking forward to using this feature on my android app

**Comment by kyo504** [comment]
Sorry for late response. I guess it works fine now. If you have any issue, feel free to re-open.

**Comment by duylinhdang1998** [comment]
Not working on android TV
