### ISSUE TITLE
vertical not supported? 

### ISSUE THREAD

**Issue by gilra2000** [kyo504/react-native-marquee#2]
vertical not supported?

**Comment by kyo504** [comment]
@gilra2000 Hi, could you provide any sample animation that behaves what you expect?

**Comment by gilra2000** [comment]
@kyo504 thanks 
[https://www.youtube.com/watch?v=ILdzhq8IjFo](url) 
00:15 start please

**Comment by kyo504** [comment]
This is not currently supported but PR is welcome.
